plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.allnewmts'
version = '0.0.1'

def reactNativeArchitectures() {
  def value = project.getProperties().get('reactNativeArchitectures')
  return value ? value.split(',') : ['armeabi-v7a', 'x86', 'x86_64', 'arm64-v8a']
}

expoModule {
  canBePublished false
}

android {
  namespace 'com.allnewmts.lua'

  defaultConfig {
    versionCode 1
    versionName '0.0.1'
    externalNativeBuild {
      cmake {
        abiFilters(*reactNativeArchitectures())
      }
    }
  }

  externalNativeBuild {
    cmake {
      path 'CMakeLists.txt'
    }
  }
}
